spring.application.name=smart-tailor-BE
server.port=6969
spring.datasource.url=jdbc:mysql://localhost:3306/smart_tailor_BE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#OAUTH2
spring.security.oauth2.client.registration.google.clientId=1051460649548-ijlrpmgdcmd5td1apidcpauh3dhv7u26.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.clientSecret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.facebook.client-id=434629229188675
spring.security.oauth2.client.registration.facebook.client-secret=c58323b814a2a31d4680008faaaaa30e
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
#JWT
application.security.jwt.secret-key=y1KJOk+zRelneGgg4cVhAoAvRmwxOkGZyCi6dcHnNYl/p+d170Av17/pqLma7HNI
# a day for jwt access token expiration for one day
application.security.jwt.expiration=86400000
# a day for jwt refresh token  expiration for 7 days
application.security.jwt.refresh-token.expiration=604800000
#STMP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smarttailor.tttm@gmail.com
spring.mail.password=aarmramwhhutitlx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=20MB
# Max Request Size
spring.servlet.multipart.max-request-size=20MB
PAYOS_CREATE_PAYMENT_LINK_URL=https://api-merchant.payos.vn/v2/payment-requests
PAYOS_CLIENT_ID=339a703f-b5c3-4c1b-b30e-c776ae2b881e
PAYOS_API_KEY=c64c9846-1eab-4b9d-8a8c-53b242e0c6f4
PAYOS_CHECKSUM_KEY=468cbcdcd6630412d201ca0b54d5ec44bb6513e1124a8b2c42077dd799835e58
BRAND_PAYOS_CLIENT_ID=a215c244-cffd-4b06-9e93-8c1d2fcc6070
BRAND_PAYOS_API_KEY=ba01ae8d-d649-4251-8951-4f4bd74220e0
BRAND_PAYOS_CHECKSUM_KEY=8d0e5ea88e1ccdb87585ae13c7d98dba56b80fdbabc050106e86f5be8e9e6d24
VNPAY_TMN_CODE=Y4I09HOS
VNPAY_CHECKSUM_KEY=ARM3J6JB3FYN8J5THUQJAXSQSDQROKFX
VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
VNPAY_API_URL=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
client.server.link=http://localhost:3000/brand/manage_order_request
CLIENT_URL=http://localhost:3000
SERVER_URL=http://localhost:6969
